# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# Workflow for asset building
name: Build Live Theme

on:
  push:
    branches:
      - 'main'
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WF_ACTION_TOKEN }}
          fetch-depth: 0
      # GITHUB_REF print
      - name: Print GITHUB_REF
        run: echo "The GITHUB_REF is: $GITHUB_REF"

      - name: Extract branch name
        run: echo "The branch name is: ${GITHUB_REF#refs/*/}"    
      # Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      # Setup git config
      - name: setup git config
        if: ${{ contains(github.ref, 'pull') }}
        run: |
          # setup the username and email.
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          # setup alias to theme repo.
          git remote add -f theme-origin https://github.com/${GITHUB_REPOSITORY}-theme.git
          git subtree pull --prefix=theme theme-origin ${GITHUB_HEAD_REF} --squash

      # Setup git config
      - name: setup git config
        if: ${{ !contains(github.ref, 'pull') }}
        run: |
          # setup the username and email.
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          # setup alias to theme repo.
          git remote add -f theme-origin https://github.com/${GITHUB_REPOSITORY}-theme.git
          git subtree pull --prefix=theme theme-origin ${GITHUB_REF#refs/*/} --squash

      - name: Build assets
        run: |
          npm run build:assets
          git log -1
          bash commit-if-not-empty
          git log -1

      # Generate production files and push those
      - name: Push production assets
        if: ${{ contains(github.ref, 'pull') }}
        run: |
          # Push production assets to theme repo.
          git subtree push --prefix theme theme-origin ${GITHUB_HEAD_REF}

      - name: Push production assets
        if: ${{ !contains(github.ref, 'pull') }}
        run: |
          # Push production assets to theme repo.
          git subtree push --prefix theme theme-origin ${GITHUB_REF#refs/*/}
