# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# Workflow for asset building
name: Create Theme in Testing Site

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WF_ACTION_TOKEN }}
          fetch-depth: 0

      # Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      # Setup git config
      - name: setup git config
        if: ${{ contains(github.ref, 'pull') }}
        run: |
          # setup the username and email.
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          # setup alias to theme repo.
          git remote add -f theme-origin https://github.com/${GITHUB_REPOSITORY}-theme.git
          git subtree pull --prefix=theme theme-origin main 

      # Setup git config
      - name: setup git config
        if: ${{ !contains(github.ref, 'pull') }}
        run: |
          # setup the username and email.
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          # setup alias to theme repo.
          git remote add -f theme-origin https://github.com/${GITHUB_REPOSITORY}-theme.git
          git subtree pull --prefix=theme theme-origin main 

      - name: Build assets
        run: npm run build:assets

      # Generate production files and push those
      - name: Push built assets
        if: ${{ contains(github.ref, 'pull') }}
        run: |
          # Push built assets to theme repo.
          npm run build:deploy -- --branch="${GITHUB_HEAD_REF}" --shopifyDeployKey="${{ secrets.SHOPIFY_PASSWORD_TESTING }}" --shopifyClientId="${{ secrets.SHOPIFY_KEY_TESTING }}" --shopifyStore="${{ secrets.SHOPIFY_URL_TESTING }}" --ngrokToken="${{ secrets.NGROK_TOKEN }}" --env="production"

      - name: Push built assets
        if: ${{ !contains(github.ref, 'pull') }}
        run: |
          # Push built assets to theme repo.
          npm run build:deploy -- --branch="${GITHUB_REF#refs/*/}" --shopifyDeployKey="${{ secrets.SHOPIFY_PASSWORD_TESTING }}" --shopifyClientId="${{ secrets.SHOPIFY_KEY_TESTING }}" --shopifyStore="${{ secrets.SHOPIFY_URL_TESTING }}" --ngrokToken="${{ secrets.NGROK_TOKEN }}" --env="production"
